apps/album/urls.py
from django.urls import path
from . import views

app_name = 'album'

urlpatterns = [
    path('<int:album>/musicas/', views.MusicaView.as_view(), name='arquivos_musicais'),
    path('genero/', views.AddEstilo.as_view(), name='add_estilo'),
    path('lista/generos/', views.ListaEstilos.as_view(), name='lista_estilos'),
    path('adicionar/', views.AddAlbum.as_view(), name='add_album'),
    path('lista/', views.ListaAlbuns.as_view(), name='lista_albuns'),
    path('songs/<int:album>/', views.MusicasLista.as_view(), name='musicas'),
    ####
    path('genero/<str:nacionalidade>/', views.Nacionalidade.as_view(), name='nacionalidade'),
    path('<str:estilo>/genero/', views.Genero.as_view(), name='genero'),
    ## REST API ##

    path('api/v1/estilos/', views.EstilosApiView.as_view(), name='estilos_serial'),
    path('api/v1/estilo/<int:pk>/', views.EstiloApiView.as_view(), name='estilo_serial'),
    path('api/v1/albuns/', views.AlbunsApiView.as_view(), name='albuns_serial'),
    path('api/v1/selecao/estilo/albuns/<int:pk>/', views.AlbunsEstiloApiView.as_view(), name='albuns_estilo_serial'),
    path('api/v1/album/<int:pk>/', views.AlbumApiView.as_view(), name='album_serial'),
    path('api/v1/musicas/', views.MusicasApiView.as_view(), name='musicas_serial'),
    path('api/v1/musica/<int:pk>/', views.MusicaApiView.as_view(), name='musica_serial'),
    #path('api/v1/musicas/6', views.LewisApiView.as_view(), name='lewis_serial'),
]

musicas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('apps.core.urls', namespace='core')),
    path('album/', include('apps.album.urls', namespace='album')),
    path('users/', include('apps.usuarios.urls', namespace='users')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/album/models.py
from django.db import models
from stdimage import StdImageField
from ..core.models import Usuario

# Create your models here.


class Estilo(models.Model):

    NACIONALIDADE = [
        ('NACIONAL', 'Nacional'),
        ('INTERNACIONAL', 'Internacional'),

    ]

    estilo = models.CharField(verbose_name='Gênero', max_length=155)
    nacionalidade = models.CharField(verbose_name='Nacionalidade', max_length=50, choices=NACIONALIDADE)

    def __str__(self):
        return self.estilo

    class Meta:
        verbose_name = 'Gênero'
        verbose_name_plural = 'Gêneros'


class Album(models.Model):
    nome_album = models.CharField(verbose_name='Álbum', max_length=200)
    capa = StdImageField(upload_to='capa/album', variations={'thumbnail': {'width': 400, 'height': 400}},
                         null=True, blank=True, delete_orphans=True)
    usuario = models.ForeignKey(Usuario, on_delete=models.DO_NOTHING)
    estilo = models.ForeignKey(Estilo, on_delete=models.DO_NOTHING)
    cantor = models.CharField(verbose_name='Cantor', max_length=255)
    status = models.BooleanField(verbose_name='Status', default=True)
    criado = models.DateTimeField(auto_now_add=True)
    atualizado = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nome_album

    def imagem(self):
        if self.capa:
            return True
        else:
            return False

    class Meta:
        verbose_name = 'Álbum'
        verbose_name_plural = 'Álbuns'


class Musica(models.Model):
    musica = models.CharField(verbose_name='Música', max_length=200)
    arquivo_musical = models.FileField(upload_to='arquivos/musicas', verbose_name='Upload Arquivo')
    album = models.ForeignKey(Album, on_delete=models.CASCADE, related_name='musica_album')
    status = models.BooleanField(verbose_name='Status', default=True)
    criado = models.DateTimeField(auto_now_add=True)
    atualizado = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.musica

    class Meta:
        verbose_name = 'Música'
        verbose_name_plural = 'Músicas'

apps/album/forms.py
from django import forms
from .models import Musica


class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True


class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = single_file_clean(data, initial)
        return result


class MusicaForm(forms.Form):
    arquivo_musical = MultipleFileField()

    class Meta:
        model = Musica
        fields = ('musica', 'arquivo_musical', 'album')

apps/album/views.py
from rest_framework import generics
from .serializers import EstiloSerializer, AlbumSerializer, MusicaSerializer
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView
from django.views.generic.edit import FormView, CreateView

from .forms import MusicaForm
from .models import Estilo, Album, Musica
from ..core.models import Usuario
import unicodedata


class AddEstilo(CreateView):
    model = Estilo
    fields = ('estilo', 'nacionalidade')
    template_name = 'album/estilo_add.html'
    success_url = '/'


class ListaEstilos(ListView):
    model = Estilo
    template_name = 'album/lista_estilos.html'
    context_object_name = 'estilos'


class AddAlbum(LoginRequiredMixin, CreateView):
    model = Album
    fields = ('nome_album', 'capa', 'estilo', 'cantor')
    template_name = 'album/album_add.html'

    def form_valid(self, form):
        album = form.save(commit=False)
        usuario = Usuario.objects.get(pk=self.request.user.id)
        album.usuario = usuario
        album.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('album:arquivos_musicais', kwargs={'album': self.object.id})


class ListaAlbuns(ListView):
    model = Album
    template_name = 'album/lista_albuns.html'
    context_object_name = 'albuns'
    ordering = ('-atualizado',)


class MusicaView(FormView):
    form_class = MusicaForm
    template_name = "album/add_musica.html"  # Replace with your template.

    def get_success_url(self):
        return reverse('album:musicas', kwargs={'album': self.kwargs['album']})

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        files = form.cleaned_data["arquivo_musical"]
        album = Album.objects.get(id=self.kwargs['album'])

        for file in files:
            m = f'{file}'
            m2 = f'{file}'
            titulo_musica = m.replace(".mp3", "")

            processamento_2 = unicodedata.normalize("NFD", m2)
            processamento_2 = processamento_2.encode("ascii", "ignore")
            processamento_2 = processamento_2.decode("utf-8")

            file.name = processamento_2
            musica = Musica.objects.create(musica=titulo_musica, arquivo_musical=file, album=album)
        return super().form_valid(form)


class MusicasLista(ListView):
    model = Musica
    template_name = 'album/musicas.html'
    context_object_name = 'musicas'

    def get_queryset(self):
        album = Album.objects.get(pk=self.kwargs['album'])
        return Musica.objects.filter(album=album)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        album = Album.objects.get(pk=self.kwargs['album'])
        context['album'] = album
        return context


class Nacionalidade(ListView):
    model = Album
    template_name = 'album/generos.html'
    context_object_name = 'albuns'


    def get_queryset(self):
        generos = Estilo.objects.filter(nacionalidade=self.kwargs['nacionalidade'])
        return Album.objects.filter(estilo__in=generos).order_by('-atualizado')


class Genero(ListView):
    model = Album
    template_name = 'album/generos_especificos.html'
    context_object_name = 'albuns'


    def get_queryset(self):
        generos = Estilo.objects.filter(estilo=self.kwargs['estilo'])
        return Album.objects.filter(estilo__in=generos).order_by('-atualizado')


###### SERIALIZERS #####

class EstilosApiView(generics.ListCreateAPIView):
    queryset = Estilo.objects.all()
    serializer_class = EstiloSerializer


class EstiloApiView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Estilo.objects.all()
    serializer_class = EstiloSerializer


class AlbunsApiView(generics.ListCreateAPIView):
    queryset = Album.objects.all()
    serializer_class = AlbumSerializer


class AlbunsEstiloApiView(generics.ListCreateAPIView):
    serializer_class = AlbumSerializer

    def get_queryset(self):
        estilo = Estilo.objects.get(pk=self.kwargs['pk'])
        return Album.objects.filter(estilo=estilo)

class AlbumApiView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Album.objects.all()
    serializer_class = AlbumSerializer


class MusicasApiView(generics.ListCreateAPIView):
    queryset = Musica.objects.all()
    serializer_class = MusicaSerializer


class MusicaApiView(generics.ListCreateAPIView):
    serializer_class = MusicaSerializer

    def get_queryset(self):
        album = Album.objects.get(pk=self.kwargs['pk'])
        return Musica.objects.filter(album=album)

apps/album/templates/album/add_musica.html
{% extends 'base/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block titulo %}Adicionar Músicas{% endblock %}
{% block conteudo %}
{% block estilo %}
<script src="https://code.jquery.com/jquery-3.7.0.js"
        integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=" crossorigin="anonymous"></script>
{% endblock %}
<div class="container-fluid">
    <img src="{% static  'images/musica.png'%}" class="img-fluid">
</div>
<div class="container" style="margin-top:20px;">
  <div class="card">
  <div class="card-body">
    <h4 class="card-title text-center">Adicionar</h4>
    <hr>
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="progress">
      <div class="progress-bar" role="progressbar" style="width: 0%;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
    </div><br>
    <button type="submit" class="btn btn-outline-primary">Salvar</button>
    </form>
  </div>
</div>
</div>
<script>
  $(document).ready(function() {
    $('form').submit(function(event) {
      event.preventDefault();  // Impede o envio padrão do formulário

      var form = $(this);
      var formData = new FormData(form[0]);

      $.ajax({
        url: form.attr('action'),
        type: form.attr('method'),
        data: formData,
        processData: false,
        contentType: false,
        xhr: function() {
          var xhr = new window.XMLHttpRequest();

          // Manipulador de progresso
          xhr.upload.addEventListener("progress", function(evt) {
            if (evt.lengthComputable) {
              var percentComplete = (evt.loaded / evt.total) * 100;
              $('.progress-bar').css('width', percentComplete + '%');
              $('.progress-bar').attr('aria-valuenow', percentComplete);
            }
          }, false);

          return xhr;
        },
        success: function(data) {
          // Lógica a ser executada em caso de sucesso
          // por exemplo, redirecionar para uma página de sucesso
          window.location.href = "{{ success_url }}";
        },
        error: function(xhr, ajaxOptions, thrownError) {
          // Lógica a ser executada em caso de erro
          console.log(xhr.responseText);
        }
      });
    });
  });
</script>

{% endblock %}

apps/album/templates/album/album_add.html
{% extends 'base/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block titulo %}Adicionar Album{% endblock %}
{% block conteudo %}
<div class="container-fluid">
    <img src="{% static  'images/album.png'%}" class="img-fluid">
</div>
<div class="container" style="margin-top:20px;">
  <div class="card">
  <div class="card-body">
    <h4 class="card-title text-center">Cadastrar</h4>
    <hr>
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-outline-primary">Salvar</button>
    </form>
  </div>
</div>
</div>
{% endblock %}

apps/album/templates/album/estilo_add.html
{% extends 'base/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block titulo %}Adicionar Estilo{% endblock %}
{% block conteudo %}
<div class="container-fluid">
    <img src="{% static  'images/genero.png'%}" class="img-fluid">
</div>
<div class="container-fluid" style="margin-top:20px;">
  <div class="card" style="background-color: #fdfdfd;">
  <div class="card-body">
    <h4 class="card-title text-center">Cadastrar</h4>
    <hr>
    <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-outline-primary">Salvar</button>
    </form>
  </div>
</div>
</div>
{% endblock %}

apps/album/templates/album/generos.html
{% extends 'base/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block titulo %}Gênero por Nacionalidade{% endblock %}
{% block estilo %}
<script src="https://cdn.jsdelivr.net/npm/masonry-layout@4.2.2/dist/masonry.pkgd.min.js" integrity="sha384-GNFwBvfVxBkLMJpYMOABq3c+d3KnQxudP/mGPkzpZSTYykLBNsZEnG2D9G/X/+7D" crossorigin="anonymous" async></script>
<style>
.gallery_product {
    margin-bottom: 30px;
    position: relative;
}

.gallery_product .texto {
    color: #fff;
    margin: 0;
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
}

@media (max-width: 767px) {
    /* Estilos específicos para telas menores */
    .gallery_product .texto {
        font-size: 16px; /* Tamanho de fonte menor para telas menores */
        top: 40%; /* Ajuste de posicionamento para telas menores */
    }
}
</style>

{% endblock %}
{% block conteudo %}
<div class="container-fluid">
     <div class="gallery_product">
        <a data-toggle="modal" data-target="#exampleModal" href="#" ><img class="img-fluid" src="{% static  'images/bg.png'%}"></a>
        <h1 class="texto title fw-bold">{{albuns.0.estilo.nacionalidade}}</h1>
     </div>
</div>
<div class="container-fluid" style="margin-top:20px;">
  <div class="row" data-masonry='{"percentPosition": true }'>
{% for album in albuns %}
    <div class="col-sm-6 col-lg-4 mb-4">
      <div class="card">
        {% if  album.imagem %}
        <img class="img-thumbnail" src="{{album.capa.thumbnail.url}}">
        {% else %}
        <img class="img-thumbnail" src="{% static 'images/music.jpg'%}">
        {% endif %}
        <div class="card-body">
          <h5 class="card-title">{{album}}</h5>
          <p class="card-text">{{album.cantor}}</p>
          <p class="card-text">{{album.estilo}}</p>
          <div class="d-grid gap-2">
            <a href="{% url 'album:musicas' album=album.id %}" class="btn btn-block btn-outline-success btn-sm ">Ver Álbum</a>
            {% if user.is_authenticated %}
            <a href="{% url 'album:arquivos_musicais' album=album.id %}" class="btn btn-block btn-outline-primary btn-sm ">Adicionar Músicas</a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
{% empty %}
    <p>Vazio</p>
{% endfor %}
  </div>
</div>
{% endblock %}

apps/album/templates/album/generos_especificos.html
{% extends 'base/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block titulo %}Gênero{% endblock %}
{% block estilo %}
<script src="https://cdn.jsdelivr.net/npm/masonry-layout@4.2.2/dist/masonry.pkgd.min.js" integrity="sha384-GNFwBvfVxBkLMJpYMOABq3c+d3KnQxudP/mGPkzpZSTYykLBNsZEnG2D9G/X/+7D" crossorigin="anonymous" async></script>
<style>
.gallery_product {
    margin-bottom: 30px;
    position: relative;
}

.gallery_product .texto {
    color: #fff;
    margin: 0;
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
}

@media (max-width: 767px) {
    /* Estilos específicos para telas menores */
    .gallery_product .texto {
        font-size: 16px; /* Tamanho de fonte menor para telas menores */
        top: 40%; /* Ajuste de posicionamento para telas menores */
    }
}
</style>

{% endblock %}
{% block conteudo %}
<div class="container-fluid">
     <div class="gallery_product">
        <a data-toggle="modal" data-target="#exampleModal" href="#" ><img class="img-fluid" src="{% static  'images/bg.png'%}"></a>
        <h1 class="texto title fw-bold">{{albuns.0.estilo}}</h1>
     </div>
</div>
<div class="container-fluid" style="margin-top:20px;">
  <div class="row" data-masonry='{"percentPosition": true }'>
{% for album in albuns %}
    <div class="col-sm-6 col-lg-4 mb-4">
      <div class="card">
        {% if  album.imagem %}
        <img class="img-thumbnail" src="{{album.capa.thumbnail.url}}">
        {% else %}
        <img class="img-thumbnail" src="{% static 'images/music.jpg'%}">
        {% endif %}
        <div class="card-body">
          <h5 class="card-title">{{album}}</h5>
          <p class="card-text">{{album.cantor}}</p>
          <p class="card-text">{{album.estilo}}</p>
          <div class="d-grid gap-2">
            <a href="{% url 'album:musicas' album=album.id %}" class="btn btn-block btn-outline-success btn-sm ">Ver Álbum</a>
            {% if user.is_authenticated %}
            <a href="{% url 'album:arquivos_musicais' album=album.id %}" class="btn btn-block btn-outline-primary btn-sm ">Adicionar Músicas</a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
{% empty %}
    <p>Vazio</p>
{% endfor %}
  </div>
</div>
{% endblock %}

apps/album/templates/album/lista_albuns.html
{% extends 'base/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block titulo %}Adicionar Album{% endblock %}
{% block estilo %}
<script src="https://cdn.jsdelivr.net/npm/masonry-layout@4.2.2/dist/masonry.pkgd.min.js" integrity="sha384-GNFwBvfVxBkLMJpYMOABq3c+d3KnQxudP/mGPkzpZSTYykLBNsZEnG2D9G/X/+7D" crossorigin="anonymous" async></script>
{% endblock %}
{% block conteudo %}
<div class="container-fluid" style="margin-top:60px;">
    <img src="{% static  'images/albuns.jpeg'%}" class="img-fluid">
</div>
<div class="container" style="margin-top:20px;">
  <div class="row" data-masonry='{"percentPosition": true }'>
{% for album in albuns %}
    <div class="col-sm-6 col-lg-4 mb-4">
      <div class="card">
        {% if  album.imagem %}
        <img class="img-thumbnail" src="{{album.capa.thumbnail.url}}">
        {% else %}
        <img class="img-thumbnail" src="{% static 'images/music.jpg'%}">
        {% endif %}
        <div class="card-body">
          <h5 class="card-title">{{album}}</h5>
          <p class="card-text">{{album.cantor}}</p>
          <p class="card-text">{{album.estilo}}</p>
          <div class="d-grid gap-2">
            <a href="{% url 'album:musicas' album=album.id %}" class="btn btn-block btn-outline-success btn-sm ">Ver Álbum</a>
            <a href="{% url 'album:arquivos_musicais' album=album.id %}" class="btn btn-block btn-outline-primary btn-sm ">Adicionar Músicas</a>
          </div>
        </div>
      </div>
    </div>
{% empty %}
    <p>Vazio</p>
{% endfor %}
  </div>
</div>
{% endblock %}

apps/album/templates/album/lista_estilos.html
{% extends 'base/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block titulo %}Lista Estilos{% endblock %}
{% block conteudo %}
<div class="container-fluid">
    <img src="{% static  'images/generos.png'%}" class="img-fluid">
</div>
<div class="container-fluid" style="margin-top:20px;">
    <table class="table table-hover table-responsive">
        <thead class="bg-primary">
        <tr>
            <th scope="col" class="text-white">#</th>
            <th scope="col" class="text-white">ESTILO</th>
            <th scope="col" class="text-white text-center">PESQUISAR</th>
        </tr>
        </thead>
        {% for estilo in estilos %}
        <tbody>
        <tr>
            <th scope="row" class="text-primary">{{forloop.counter}}</th>
            <td class="text-dark">{{estilo}}</td>
            <td class="text-dark text-center"><a href="{% url 'album:genero' estilo=estilo %}"><i class="bi bi-box-arrow-in-right"></i></a></td>
        </tr>
        </tbody>
        {% empty %}
        <p>Vazio</p>
        {% endfor %}
    </table>
</div>
<hr>
{% endblock %}

apps/album/templates/album/musicas.html
{% extends 'base/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block titulo %}Musicas{% endblock %}
{% block conteudo %}
<div class="container-fluid">
    <img src="{% static  'images/playlist.png'%}" class="img-fluid">
    <hr>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-4" style="margin-bottom:20px;">
        <div class="card">
          {% if  album.imagem %}
          <img class="img-thumbnail" src="{{album.capa.thumbnail.url}}">
          {% else %}
          <img class="img-thumbnail" src="{% static 'images/music.jpg'%}">
          {% endif %}
          <div class="card-body">
            <h5 class="card-title text-center">{{album}}</h5>
            <p class="card-text text-center">{{album.cantor}}</p>
        <div class="col text-center">
          <button onclick="previousSong()" class="btn btn-primary"><i class="bi bi-skip-start-fill"></i></button>
          <button onclick="pauseAudio()" class="btn btn-primary"><i class="bi bi-pause-fill"></i></button>
          <button onclick="playAudio()" class="btn btn-primary"><i class="bi bi-play-fill"></i></button>
          <button onclick="nextSong()" class="btn btn-primary"><i class="bi bi-skip-end-fill"></i></button>
          <audio id="audioPlayer"></audio>
        </div>
          </div>
        </div>
    </div>
    <div class="col-md-8">
      <table class="table table-responsive table-hover">
        <thead class="bg-primary">
          <tr>
            <th scope="col" class="text-white">#</th>
            <th scope="col" class="text-white">MÚSICA</th>
            <th scope="col" class="text-white text-center">TOCAR</th>
          </tr>
        </thead>
        <tbody>
          {% for musica in musicas %}
          <tr id="{{musica.id}}">
            <th scope="row" class="text-primary">{{forloop.counter}}</th>
            <td class="text-dark">{{musica}}</td>
            <td class="text-dark text-center">
              <audio controls class="w-100">
                <source src="{{musica.arquivo_musical.url}}" type="audio/mpeg">
              Your browser does not support the audio element.
              </audio>
            </td>
          </tr>
          {% empty %}
          <p>Vazio</p>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
  <script>
    var audio = document.getElementById("audioPlayer");
    var songs = [];  // Array para armazenar as informações das músicas
    var currentSongIndex = 0;  // Índice da música atual

    // Função para carregar as músicas no array
    function loadSongs() {
      // Aqui você pode usar o Django para recuperar as músicas do backend
      // e adicionar os dados das músicas ao array "songs"
      {% for musica in musicas %}
        songs.push({
          title: "{{ musica.musica }}",
          src: "{{ musica.arquivo_musical.url }}"
        });
      {% endfor %}
    }

    // Função para reproduzir a música atual
    function playAudio() {
      if (audio.src === "") {
        loadSongs();  // Carrega as músicas se ainda não foram carregadas
        audio.src = songs[currentSongIndex].src;
      }
      audio.play();
    }

    // Função para pausar a reprodução
    function pauseAudio() {
      audio.pause();
    }

    // Função para avançar para a próxima música
    function nextSong() {
      currentSongIndex++;
      if (currentSongIndex >= songs.length) {
        currentSongIndex = 0;  // Volta para a primeira música se já estiver na última
      }
      audio.src = songs[currentSongIndex].src;
      audio.play();
    }

    // Função para voltar para a música anterior
    function previousSong() {
      currentSongIndex--;
      if (currentSongIndex < 0) {
        currentSongIndex = songs.length - 1;  // Vai para a última música se já estiver na primeira
      }
      audio.src = songs[currentSongIndex].src;
      audio.play();
    }

    // Reprodução automática quando uma música é clicada
    audio.addEventListener("ended", nextSong);

    document.addEventListener('play', function(e){
    var audios = document.getElementsByTagName('audio');
    for(var i = 0, len = audios.length; i < len;i++){
        if(audios[i] != e.target){
            audios[i].pause();
        }
    }
}, true);
  </script>
{% endblock %}