apps/album/urls.py
from django.urls import path
from . import views

app_name = 'album'

urlpatterns = [
    path('<int:album>/musicas/', views.MusicaView.as_view(), name='arquivos_musicais'),
    path('genero/', views.AddEstilo.as_view(), name='add_estilo'),
    path('lista/generos/', views.ListaEstilos.as_view(), name='lista_estilos'),
    path('adicionar/', views.AddAlbum.as_view(), name='add_album'),
    path('lista/', views.ListaAlbuns.as_view(), name='lista_albuns'),
    path('songs/<int:album>/', views.MusicasLista.as_view(), name='musicas'),
    ####
    path('genero/<str:nacionalidade>/', views.Nacionalidade.as_view(), name='nacionalidade'),
    path('<str:estilo>/genero/', views.Genero.as_view(), name='genero'),
    ## REST API ##

    path('api/v1/estilos/', views.EstilosApiView.as_view(), name='estilos_serial'),
    path('api/v1/estilo/<int:pk>/', views.EstiloApiView.as_view(), name='estilo_serial'),
    path('api/v1/albuns/', views.AlbunsApiView.as_view(), name='albuns_serial'),
    path('api/v1/selecao/estilo/albuns/<int:pk>/', views.AlbunsEstiloApiView.as_view(), name='albuns_estilo_serial'),
    path('api/v1/album/<int:pk>/', views.AlbumApiView.as_view(), name='album_serial'),
    path('api/v1/musicas/', views.MusicasApiView.as_view(), name='musicas_serial'),
    path('api/v1/musica/<int:pk>/', views.MusicaApiView.as_view(), name='musica_serial'),
    #path('api/v1/musicas/6', views.LewisApiView.as_view(), name='lewis_serial'),
]

apps/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.Index.as_view(), name='home'),
]

musicas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('apps.core.urls', namespace='core')),
    path('album/', include('apps.album.urls', namespace='album')),
    path('users/', include('apps.usuarios.urls', namespace='users')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/core/models.py
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser
from django.db import models

# Create your models here.


class UsuarioManager(BaseUserManager):
    def create_user(self, email, nome, password=None):
        if not email:
            raise ValueError('Digite um email válido.')

        user = self.model(
            email=self.normalize_email(email),
            nome=nome,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, nome, password=None):
        user = self.create_user(
            email,
            password=password,
            nome=nome,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class Usuario(AbstractBaseUser):
    email = models.EmailField(verbose_name='Email', max_length=255, unique=True)
    nome = models.CharField(verbose_name='Nome Usuario', max_length=255)
    is_active = models.BooleanField(default=True)
    is_administrator = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    cadastrado_em = models.DateTimeField(auto_now_add=True)
    atualizado_em = models.DateTimeField(auto_now=True)

    objects = UsuarioManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['nome']

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

apps/core/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.core.exceptions import ValidationError

from ..core.models import Usuario


class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Senha', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirme a senha', widget=forms.PasswordInput)

    class Meta:
        model = Usuario
        fields = ('email', 'nome')

    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)
        self.fields['nome'].label = "Nome"

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError("Senhas não coincidem.")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = Usuario
        fields = ('email', 'password', 'nome', 'is_active', 'is_admin')

apps/core/views.py
from django.shortcuts import render
from django.views.generic import ListView
from ..album.models import Album


# Create your views here.


class Index(ListView):
    model = Album
    template_name = 'core/home.html'
    context_object_name = 'albuns'

    def get_queryset(self):
        return Album.objects.filter().order_by('-atualizado')[:6]

apps/core/templates/core/home.html
{% extends 'base/base.html' %}
{% load static %}
{% block titulo %}Home{% endblock %}
{% block estilo %}
<link rel="stylesheet" type="text/css" href="{% static 'carousel/carousel.css' %}">

{% endblock %}
{% block conteudo %}

<div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="{% static 'images/guitar.jpg' %}" alt="">
            <div class="container">
                <div class="carousel-caption text-start">
                    <h1>Internacional</h1>
                    <p>Lista de álbuns que são sucessos <br>internacionais</p>
                    <p><a class="btn btn-lg btn-primary" href="#">Ver Álbuns</a></p>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <img src="{% static 'images/guitar.jpg' %}" alt="">
            <div class="container">
                <div class="carousel-caption text-start">
                    <h1>Nacionais</h1>
                    <p>Os álbuns que são os maiores sucessos nacionais.
                        <br>Venha conferir</p>
                    <p><a class="btn btn-lg btn-primary" href="#">Ver Álbuns</a></p>
                </div>
            </div>
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>
<div class="container bg-white">
    <h1 class="display-6 text-center text-primary">Álbuns Recentes</h1>
</div>
<div class="album py-5 bg-light">
    <div class="container bg-white">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for album in albuns %}
            <div class="col">
                <div class="card shadow-sm">
                    <img src="{{album.capa.thumbnail.url}}">
                    <div class="card-body">
                        <h6 class="card-text text-center fw-semibold text-primary">{{album}}</h6>
                                <div class="d-grid gap-2">
                                    <a href="{% url 'album:musicas' album=album.id %}" class="btn btn-block btn-outline-primary btn-sm ">Ver Álbum</a>
                                 </div>
                    </div>
                </div>
            </div>
            {% empty %}
            <p>Vazio..</p>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}